### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by suyog250592** [aseveryn/deep-qa#11]
After running 'run_build_datasets.sh' all the files were generated inside TRAIN and TRAIN-ALL folder, but when i am trying to train the network with 'python run_nnet.py TRAIN' or 'python run_nnet.py TRAIN-ALL', it is stopping after printing 'Generating adadelta updates' (see below)

*********
Zero out dummy word: True
  1%|▎                                         | 8/1122 [00:03<08:00,  2.32it/s]
Floating point exception (core dumped)
********
can someone help me out with this?

**Comment by suyog250592** [comment]
It was a memory issue, working fine on GPU.

**Comment by zyn412** [comment]
hi,i can't download the pre-initialized word2vec embedding.
i can't open that link.
Could you please send that data to my email?
