### ISSUE TITLE
pip install numba --user   failed

### ISSUE THREAD

**Issue by loveJasmine** [aseveryn/deep-qa#6]
envy@ub1404:/media/envy/data1t/os_prj/github/deep-qa$ pip install numba --user
Requirement already satisfied (use --upgrade to upgrade): numba in /home/envy/.local/lib/python2.7/site-packages
Downloading/unpacking llvmlite (from numba)
  Downloading llvmlite-0.10.0.tar.gz (92kB): 92kB downloaded
  Running setup.py (path:/tmp/pip_build_envy/llvmlite/setup.py) egg_info for package llvmlite

Requirement already satisfied (use --upgrade to upgrade): numpy in /home/envy/.local/lib/python2.7/site-packages (from numba)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /home/envy/.local/lib/python2.7/site-packages (from numba)
Downloading/unpacking singledispatch (from numba)
  Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl
Downloading/unpacking funcsigs (from numba)
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in /home/envy/.local/lib/python2.7/site-packages (from singledispatch->numba)
Installing collected packages: llvmlite, singledispatch, funcsigs
  Running setup.py install for llvmlite
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

```
error: option --single-version-externally-managed not recognized
Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_envy/llvmlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4f3RJo-record/install-record.txt --single-version-externally-managed --compile --user:
usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
```

   or: -c --help [cmd1 cmd2 ...]

   or: -c --help-commands

   or: -c cmd --help

error: option --single-version-externally-managed not recognized

---

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip_build_envy/llvmlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-4f3RJo-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip_build_envy/llvmlite
Storing debug log for failure in /home/envy/.pip/pip.log
envy@ub1404:/media/envy/data1t/os_prj/github/deep-qa$

**Comment by zhezhaoa** [comment]
I also have problems in installing numba. It seems that llvmlite can not be installed correctly

**Comment by SeekPoint** [comment]
it doesn't occurs on another computer
